
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nidia
 */
public class Principal extends javax.swing.JFrame {
    Graphics gpsMiDibu;
    Point coord = null;
    int c=0;
    int x1 = 0;
    int y1 = 0;
    int x2 = 0;
    int y2 = 0;
    int xd = 0;
    int yd = 0;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        gpsMiDibu = canvasDibu.getGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvasDibu = new java.awt.Canvas();
        cerrar2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        canvasDibu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        canvasDibu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvasDibuMouseClicked(evt);
            }
        });

        cerrar2.setText("Cerrar figura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(canvasDibu, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(cerrar2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(canvasDibu, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(cerrar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canvasDibuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasDibuMouseClicked
        // TODO add your handling code here:
        gpsMiDibu.drawOval(evt.getX() - 2, evt.getY() - 2, 4, 4);
        if(coord != null){
            gpsMiDibu.drawLine(coord.x, coord.y, evt.getX(), evt.getY());
            coord.x=evt.getX();
            coord.y=evt.getY();
            xd = evt.getX();
            yd = evt.getY();
        }else{
            coord = new Point(evt.getX(), evt.getY());
        }
        if(cerrar2.isSelected()){
            gpsMiDibu.drawLine(x2, y2, xd, yd);
        }
        /*if(c==0){
            xd = evt.getX();
            yd = evt.getY();
        }
        if(c!=0){
            x2 = evt.getX()-2;
            y2 = evt.getY()-2;
            gpsMiDibu.drawLine(x1, y1, x2, y2);
            x1 = x2;
            y1 = y2;
        }else{
            x1 = evt.getX()-2;
            y1 = evt.getY()-2;
        }
        if(cerrar2.isSelected()){
            gpsMiDibu.drawLine(x2, y2, xd, yd);
        }
        c++;*/
    }//GEN-LAST:event_canvasDibuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvasDibu;
    private javax.swing.JCheckBox cerrar2;
    // End of variables declaration//GEN-END:variables
}
